name: 'Dependabot vulnerabilities alerts'
description: 'Dependabot vulnerabilities alerts from Github'
inputs:
  token: 
    description: 'Github repository token'
    required: true
  repositories: 
    description: 'Github repositories e.g. "owner/repo1,owner/repo2"'
    required: true
  output:
    description: 'Path to output file. defaults to dependabotalerts.json'
    default: 'dependabotalerts.json'
    required: true
  maxAlerts:
    description: 'Maximum alerts to fetch'
    default: 20
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
