name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    name: Test GH Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run on MTES-MCT/dashlord
      uses: ./
      with:
        token: ${{ secrets.DEPENDABOTALERTS_TOKEN }}
        repo: MTES-MCT/dashlord
        output: dependabotalerts.json
    - run: |
        cat dependabotalerts.json
